export const supabaseUrl = 'https://kxtapuebivyoqwkdhphb.supabase.co'
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4dGFwdWViaXZ5b3F3a2RocGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTUzNzg1NDQsImV4cCI6MjAzMDk1NDU0NH0.RHSytO4nnlXj6wsFi5E5TYnKMhJHPYtN_k0Nx9EQf6A'

// NEXT_PUBLIC_SUPABASE_URL=supabaseUrl;
// NEXT_PUBLIC_SUPABASE_ANON_KEY=supabaseAnonKey;